name: Release Python Package

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
    - name: Update apt-get
      run: sudo apt-get update -y
    - name: Install sndfile
      run: sudo apt-get install -y libsndfile1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install numpy==1.24.4
        pip install setuptools wheel twine sphinx
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Compile docs
      run: |
        cd docs
        make html
    - name: Build and publish
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN_CE }}
      run: |
        python setup.py sdist bdist_wheel
        twine upload dist/*
    - name: Deploy docs to GitHub pages
      uses: JamesIves/github-pages-deploy-action@4.0.0
      with:
        branch: gh-pages
        folder: docs/_build/html